### ISSUE TITLE
Import fails if sass file name matches directory name

### ISSUE THREAD

**Issue by jbrownfield** [amiramw/grunt-contrib-sassjs#2]
I believe line 20 of tasks/sass.js should be:

if (grunt.file.exists(path) && ! grunt.file.isDir(path)) {

When a partial has the same filename as a subdirectory, the directory has an exact name match which is prioritized over other name matches in Sass.js, causing the Sass compile to fail with EISDIR.

**Comment by amiramw** [comment]
The use case is partial file name _test.scss and folder name on the same level test.scss?

**Comment by amiramw** [comment]
Fixed: https://github.com/amiramw/grunt-contrib-sassjs/commit/2cf9ae9a0a7680b3274872fb7f0435118ca8aabc
